services:
  postgis:
    platform: linux/amd64
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: rides
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - .data/postgis:/var/lib/postgresql/data